### ISSUE TITLE
运行不了咋整

### ISSUE THREAD

**Issue by look0089** [zcq100/tieba-sign#1]
D:\project\tieba-sign-master>pip install --user tieba-sign
Requirement already satisfied: tieba-sign in c:\users\jyb\appdata\roaming\python\python38\site-packages (0.0.6)

D:\project\tieba-sign-master>tieba-sign -h
'tieba-sign' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

大佬教教我，我刚学 python 还不是很懂

**Comment by zcq100** [comment]
我重新发布了一个版本，你可以试试。
https://pypi.org/project/tieba-sign/

**Comment by ghost** [comment]
> 我重新发布了一个版本，你可以试试。
> https://pypi.org/project/tieba-sign/

谢谢大佬，造福人类。
